# -*- coding: utf-8 -*-
"""Untitled72.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MFGbD6SMSc7xe2ATcpehXTrmWgKGP_Mg
"""

import torch
from torch.utils.data import Dataset, DataLoader
import json
import os

class ChessTokenizer:
    def __init__(self, vocab_path="chess_vocab.json"):


        self.PAD = "[PAD]"
        self.BOS = "[BOS]"
        self.EOS = "[EOS]"
        self.UNK = "[UNK]"

        self.special_tokens = [self.PAD, self.BOS, self.EOS, self.UNK]

        if os.path.exists(vocab_path):
            self._load_vocab(vocab_path)
        else:
            self._generate_and_save_vocab(vocab_path)


        self.id2token = {v: k for k, v in self.token2id.items()}

        self.pad_id = self.token2id[self.PAD]
        self.bos_id = self.token2id[self.BOS]
        self.eos_id = self.token2id[self.EOS]
        self.unk_id = self.token2id[self.UNK]

    def _generate_moves(self):
        files = "abcdefgh"
        ranks = "12345678"
        vocab_list = []

        # 기하학적 궤적 (퀸 + 나이트)
        for f1 in range(8):
            for r1 in range(8):
                for f2 in range(8):
                    for r2 in range(8):
                        if f1 == f2 and r1 == r2: continue
                        df = abs(f1 - f2)
                        dr = abs(r1 - r2)
                        if (f1 == f2) or (r1 == r2) or (df == dr) or ((df == 2 and dr == 1) or (df == 1 and dr == 2)):
                            vocab_list.append(f"{files[f1]}{ranks[r1]}{files[f2]}{ranks[r2]}")

        # 폰 프로모션 궤적
        promotion_pieces = ['q', 'r', 'b', 'n']
        for f1 in range(8):
            for p in promotion_pieces:
                vocab_list.append(f"{files[f1]}7{files[f1]}8{p}")
                vocab_list.append(f"{files[f1]}2{files[f1]}1{p}")
            if f1 > 0:
                for p in promotion_pieces:
                    vocab_list.append(f"{files[f1]}7{files[f1-1]}8{p}")
                    vocab_list.append(f"{files[f1]}2{files[f1-1]}1{p}")
            if f1 < 7:
                for p in promotion_pieces:
                    vocab_list.append(f"{files[f1]}7{files[f1+1]}8{p}")
                    vocab_list.append(f"{files[f1]}2{files[f1+1]}1{p}")

        return sorted(vocab_list)

    def _generate_and_save_vocab(self, path):
        moves = self._generate_moves()
        all_tokens = self.special_tokens + moves

        self.token2id = {token: idx for idx, token in enumerate(all_tokens)}

        with open(path, "w", encoding="utf-8") as f:
            json.dump(self.token2id, f, indent=4)
        print(f"새로운 사전 파일이 생성되었습니다: {path} (총 토큰 수: {len(self.token2id)})")

    def _load_vocab(self, path):
        with open(path, "r", encoding="utf-8") as f:
            self.token2id = json.load(f)
        print(f"사전 파일을 성공적으로 불러왔습니다: {path}")

    def __len__(self):
        return len(self.token2id)


    def encode(self, moves_list, add_bos_eos=True):

        ids = [self.token2id.get(move, self.unk_id) for move in moves_list]

        if add_bos_eos:
            ids = [self.bos_id] + ids + [self.eos_id]

        return torch.tensor(ids, dtype=torch.long)

    def decode(self, tensor_ids, skip_special_tokens=True):

        if isinstance(tensor_ids, torch.Tensor):
            tensor_ids = tensor_ids.tolist()

        moves = []
        for idx in tensor_ids:
            token = self.id2token.get(idx, self.UNK)
            if skip_special_tokens and token in self.special_tokens:
                continue
            moves.append(token)
        return moves